export const GEOLOCATION_GEOLOCATOR_SET: string = 'GEOLOCATION_GEOLOCATOR_SET';
export const GEOLOCATION_COORDS_REGISTER: string = 'GEOLOCATION_COORDS_REGISTER';
export const GEOLOCATION_POSITION_WATCHER_FROM_MAP_REGISTER: string = 'GEOLOCATION_POSITION_WATCHER_FROM_MAP_REGISTER';

export const MAP_MAPINSTANCE_SET: string = 'MAP_MAPINSTANCE_SET';